export const UPDATE_SCREEN = 'UPDATE_SCREEN';
export const UPDATE_MENU = 'UPDATE_MENU';
export const UPDATE_PROJECTS_LIST = 'UPDATE_PROJECTS_LIST';
export const UPDATE_COMMAND_LIST = 'UPDATE_COMMAND_LIST';
export const UPDATE_MAIN_CPP = 'UPDATE_MAIN_CPP';
export const UPDATE_MAIN_CPP_VISIBILITY = 'UPDATE_MAIN_CPP_VISIBILITY';
export const UPDATE_CMD_PROMPT = 'UPDATE_CMD_PROMPT';
export const UPDATE_CMD_PROMPT_VISIBILITY = 'UPDATE_CMD_PROMPT_VISIBILITY';